### PR TITLE
chore: Update framework recommendations

### PR DESCRIPTION
**Pull request by koss-lebedev**
I renamed "project starters" into "frameworks" because without create-react-app and all the starter templates we used to recommend, all other recommendations fall under frameworks. I emphasized Next.JS as the right choice in most cases, but added Remix and Gatsby as well as they have their strengths in certain types of applications.

### CODE REVIEW

**Comment by michalhonc** [comment]
@koss-lebedev Maybe I am in a tech social bubble that is using just Next and Remix but isn't Gatsby a bit out of our reach tech-wise? They were the go-to framework for SSG but NextJS just crushed them with their suit of rendering mechanisms. Currently the only additional value contributed to Gatsby (at least on Twitter) is their broad plugin library which in my case is a con due to tight connection with the framework. So frankly I wouldn't suggest using Gatbsy to anyone but again, I would love to be proven wrong and get others opinions on this

PS love the `last note` in `## Additional information` section ❤️🦸‍♂️

**Comment by danielkraus** [comment]
@michalhonc Agree. We do have a few ongoing Gatsby projects at STRV at the moment, but I don't expect we'd ever start a new one in Gatsby again considering Next.js strength.

**Comment by koss-lebedev** [comment]
OK, maybe it's just me who still has a soft spot for Gatsby 🙂 Gatbsy is alive and striving, but I guess you're right that people who don't already know it probably wouldn't pick it over NextJS.

**Review by danielkraus — APPROVED** [review]

**Comment by danbalarin** [comment]
Can I send here an unsolicited Vite plug? I don't think it would fit into the frameworks category, but the project starters is getting removed. Anyways, I believe that Vite is a perfect project starter for projects that don't necessarily need SEO or projects that use some other framework that has its own opinionated rules and/or router. It's IMHO the best alternative to CRA, providing an easy effortless setup while having the option to tweak things. And the Vitest integration is just the cherry on top.

What I'm trying to say here is, would there be some spot for Vite where I could sum it up? And maybe after this one is merged I could do a write-up regarding Refine.dev in the frameworks category, what do you guys think?

**Comment by koss-lebedev** [comment]
Thanks for your recommendation @danbalarin ! Personally, I have zero experience with Vite, but I've seen that it's collected almost all awards in the State of JS survey this year, so maybe it deserves more recognition in STRV as well. Do you want to bring this discussion to our Slack channel to see what the general awareness/opinions of it are?

Ultimately, I think you can add both Vite and Refine to this page as it makes the most sense, but in the interest of getting things moving, I'll merge this PR since no more questions to the part I wrote seem to be coming.

**Pull request merged**
